### ISSUE TITLE
Errors while launching firefox in a debugger

### ISSUE THREAD

**Issue by nicofrand** [wallabag/firefox-ext#20]
I believe there are some issues with the extension. Here is what appears when I [launch firefox in gdb](https://framabin.org/?21bda7ea8eea627d#imrtqhTIRPcVgnaSorkUw1OLkag6cflUva2kvQh4qkE=) :

`
1442927717913   addons.manager  WARN    Exception calling callback: [Exception... "[JavaScript Error: "extension is null" {file: "chrome://wallabag/content/overlay.js" line: 48}]'[JavaScript Error: "extension is null" {file: "chrome://wallabag/content/overlay.js" line: 48}]' when calling method: [extIExtensionsCallback::callback]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: jar:file:///home/nicofrand/firefox/browser/omni.ja!/components/fuelApplication.js :: extApplication.prototype.getExtensions/< :: line 1401"  data: yes] Stack trace: extApplication.prototype.getExtensions/<()@jar:file:///home/nicofrand/firefox/browser/omni.ja!/components/fuelApplication.js:1401 < safeCall()@resource://gre/modules/AddonManager.jsm:173 < getAddonsByTypes_noMoreObjects()@resource://gre/modules/AddonManager.jsm:2399 < AOC_callNext()@resource://gre/modules/AddonManager.jsm:369 < getAddonsByTypes_concatAddons()@resource://gre/modules/AddonManager.jsm:2394 < this.Experiments.PreviousExperimentProvider.prototype<.getAddonsByTypes()@resource:///modules/experiments/Experiments.jsm:2287 < callProviderAsync()@resource://gre/modules/AddonManager.jsm:248 < getAddonsByTypes_nextObject()@resource://gre/modules/AddonManager.jsm:2389 < AOC_callNext()@resource://gre/modules/AddonManager.jsm:375 < getAddonsByTypes_concatAddons()@resource://gre/modules/AddonManager.jsm:2394 < PL_getAddonsByTypes()@resource://gre/modules/addons/PluginProvider.jsm:139 < callProviderAsync()@resource://gre/modules/AddonManager.jsm:248 < getAddonsByTypes_nextObject()@resource://gre/modules/AddonManager.jsm:2389 < AOC_callNext()@resource://gre/modules/AddonManager.jsm:375 < getAddonsByTypes_concatAddons()@resource://gre/modules/AddonManager.jsm:2394 < GMPProvider.getAddonsByTypes()@resource://gre/modules/addons/GMPProvider.jsm:592 < callProviderAsync()@resource://gre/modules/AddonManager.jsm:248 < getAddonsByTypes_nextObject()@resource://gre/modules/AddonManager.jsm:2389 < AOC_callNext()@resource://gre/modules/AddonManager.jsm:375 < getAddonsByTypes_concatAddons()@resource://gre/modules/AddonManager.jsm:2394 < LightweightThemeManager_getAddonsByTypes()@resource://gre/modules/LightweightThemeManager.jsm:446 < callProviderAsync()@resource://gre/modules/AddonManager.jsm:248 < getAddonsByTypes_nextObject()@resource://gre/modules/AddonManager.jsm:2389 < AOC_callNext()@resource://gre/modules/AddonManager.jsm:375 < getAddonsByTypes_concatAddons()@resource://gre/modules/AddonManager.jsm:2394 < getAddonsByTypes_getVisibleAddons()@resource://gre/modules/addons/XPIProvider.jsm:4022 < makeSafe/<()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:145 < asyncMap_gotValue()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:180 < asyncMap_callback()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:187 < completeAddon()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:134 < getAddon()@resource://gre/modules/addons/AddonRepository.jsm:580 < this.AddonRepository.getCachedAddonByID<()@resource://gre/modules/addons/AddonRepository.jsm:592 < next()@self-hosted:624 < TaskImpl_run()@resource://gre/modules/Task.jsm:314 < TaskImpl()@resource://gre/modules/Task.jsm:275 < createAsyncFunction/asyncFunction()@resource://gre/modules/Task.jsm:249 < getRepositoryAddon()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:136 < asyncMap_each()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:186 < map()@self-hosted:226 < asyncMap()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:184 < this.XPIDatabase.getAddonList/<()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1059 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:867 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:688 < <file:unknown>
`

**Comment by tcitworld** [comment]
We changed the extension system, so this shouldn't happen anymore. Feel free to re-open if needed.
