### ISSUE TITLE
losing parameters when upgrading to 2.0.0 

### ISSUE THREAD

**Issue by esion** [wallabag/firefox-ext#30]
I had to set my wallabag server url

Firefox 43, Iceweasel 38.4, Debian 8

**Comment by tcitworld** [comment]
Yup, we changed from the old extension system to jpm extensions.

**Comment by esion** [comment]
Feel free to close the issue if it is not relevant ;)

**Comment by tcitworld** [comment]
Well, that's too late to do something anyway. :)
