### ISSUE TITLE
Error thrown when URL instance not starting with http:// or https:// not clear enough

### ISSUE THREAD

**Issue by AugierLe42e** [wallabag/firefox-ext#37]
Since the update to Firefox 44, the Wallabag extension don't work anymore. I've configured it again with address to y Wallabag instance, but when using it, Firefox open an new tab with the message 

    Firefox can't find the file at resource://poche-at-gaulupeau-dot-fr/data/<mon_url_wallabag>?action=add&url=<url>&autoclose=true.

**Comment by tcitworld** [comment]
Does your URL starts with http:// ?

**Comment by AugierLe42e** [comment]
In the error, the URL is base64 encoded. I tested it with a https url. Decoding it gives me https URL.

**Comment by AugierLe42e** [comment]
Oh, you mean my Wallabag instance URL? Nope, it didn't. Indeed, it work, now. Though, I'd leave this issue opened for now. The extension should throw a more significant error. ;)

**Comment by tcitworld** [comment]
Will add the checking.
