### ISSUE TITLE
Blank window when adding link

### ISSUE THREAD

**Issue by swertz** [wallabag/firefox-ext#40]
Since a few days I'm getting a blank popup when trying to add something to my bag:
![temp](https://cloud.githubusercontent.com/assets/8058274/13117229/4e030ba6-d59f-11e5-8e2f-481b74d453cd.png)
My Firefox install (Kubuntu Linux 64 bits) is up-to-date. I've tried de-activating ad-blocking add-ons, nothing changed. All other webpages load fine. Accessing the bag instance directly (https://framabag.org) poses no problem.

Can someone confirm this?

**Comment by tcitworld** [comment]
Sorry. You need to set the wallabag url of your instance again in the parameters of the extension.

**Comment by swertz** [comment]
Oh, thanks! Would it be easy to print a message indicating that the url needs to be entered again, instead of having this blank window?

**Comment by Aldarone** [comment]
It's on the next release :wink:

**Comment by swertz** [comment]
Great, thanks!
