### ISSUE TITLE
How can I switch the language to English?

### ISSUE THREAD

**Issue by schiesbn** [wallabag/firefox-ext#44]
The setting of the Firefox plug-in is in English but the interaction with the plugin is in French, e.g. if I bookmark a page I see "L'article est en train d'être enregistré…". How can I switch this to English?

**Comment by tcitworld** [comment]
Are you talking about this extension ? https://addons.mozilla.org/fr/firefox/addon/wallabag-v2/
It's repository is at this address : https://github.com/ThibaudDauce/wallabag-firefox

**Comment by schiesbn** [comment]
yes, that's the extension I meant. Thanks for pointing me to the correct repository.

**Comment by nicosomb** [comment]
about this extension, maybe @ThibaudDauce agrees to add his repository in our organization.

**Comment by ThibaudDauce** [comment]
Of course I agree :-) Need to see the rights?
