### ISSUE TITLE
0.0.6 not working fpr me with wallabag > 2.0

### ISSUE THREAD

**Issue by fodiator** [wallabag/firefox-ext#45]
Hi, 
I currently have a working wallabag 2.0.3 installed. Unfortunately the firefox app is not working for me. Maybe because I have it running within a subdirectory of my webserver, which caused a problem with the android app as well. 
The latest android app is working now but from my desktop firefox I am unable to add stories. When hitting the wallagbag icon,  the login window appears, I add my credentials, window disappears but article is not added to wallabag.

Kind regards

**Comment by tcitworld** [comment]
This module is depreciated in favor of https://addons.mozilla.org/fr/firefox/addon/wallabag-v2/

**Comment by fodiator** [comment]
THX
but wallabag-v2 0.0.6 **is** the version I have mentioned

**Comment by tcitworld** [comment]
Sorry about this, could you open the issue here : https://github.com/ThibaudDauce/wallabag-firefox ?
